---
---
#python 

### try-except문
+ try 블록 수행 중 오류가 발생하면 except 블록이 수행되지만, try 블록에서 오류가 발생하지 않는다면 except 블록은 수행되지 않는다.
```python
try: 
	... 
except [발생오류 [as 오류변수]]: # 괄호 안 생략 가능
	...
```
+ 오류가 여러 개일 때도 한번에 처리할 수 있다.
```python
try:
    a = [1,2]
    print(a[3])
    4/0
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다.")
except IndexError:
    print("인덱싱 할 수 없습니다.")

```
```python
try:
    a = [1,2]
    print(a[3])
    4/0
except (ZeroDivisionError, IndexError) as e:
    print(e)

```
### try-finally 문
+ finally 절은 try 문 수행 도중 예외 발생 여부에 상관없이 항상 수행된다. 보통 finally 절은 사용한 리소스를 close해야 할 때 많이 사용한다.
```python
try:
    f = open('foo.txt', 'w')
    # 무언가를 수행한다.

    (... 생략 ...)

finally:
    f.close()  # 중간에 오류가 발생하더라도 무조건 실행된다.

```

### try-else 문
+ try 문 수행 중 오류가 발생하면 except 절, 오류가 발생하지 않으면 else 절이 수행된다.
```python
try:
    age=int(input('나이를 입력하세요: '))
except:
    print('입력이 정확하지 않습니다.')
else:
    if age <= 18:
        print('미성년자는 출입금지입니다.')
    else:
        print('환영합니다.')

```

### 오류 회피하기
+ 오류를 그냥 통과시킨다.
```python
try:
    f = open("나없는파일", 'r')
except FileNotFoundError:
    pass

```

### 오류 일부러 발생시키기
```python
# error_raise.py
class Bird:
    def fly(self):
        raise NotImplementedError

```
### 예외 만들기
```python

# error_make.py
class MyError(Exception):
    pass

def say_nick(nick):
    if nick == '바보':
        raise MyError()
    print(nick)

try:
    say_nick("천사")
    say_nick("바보")
except MyError:
    print("허용되지 않는 별명입니다.")



say_nick("천사")
say_nick("바보") # Error 발생

'''
천사
허용되지 않는 별명입니다.
'''

```